[{
	"id":1,
    "text":"首页",
    "state":"",
    "attributes":{
		"url":"",
		"iframe":""
	},
    "children":[{
    	"id":2,
        "text":"系统管理",
        "state":"",
        "attributes":{
            "url":"",
			"iframe":""
        },
        "children":[{
        	"id":3,
        	"text":"用户管理",
            "state":"",
            "attributes":{
                "url":"datagrid.html",
				"iframe":""
            }
        },{
        	"id":4,
        	"text":"角色管理",
            "state":"",
            "attributes":{
                "url":"_content.html",
				"iframe":""
            }
        },{
        	"id":5,
        	"text":"菜单管理",
            "state":"",
            "attributes":{
                "url":"datagrid.html",
				"iframe":""
            }
        },{
        	"id":6,
        	"text":"权限管理",
            "state":"",
            "attributes":{
                "url":"http://www.baidu.com",
				"iframe":"true"
            }
        }]
    }]
}]